services:
  tinyauth:
    container_name: tinyauth
    image: ghcr.io/steveiliop56/tinyauth:v5
    restart: unless-stopped
    environment:
      - TINYAUTH_APPURL=https://auth.hommers.nl
      - TINYAUTH_DATABASE_PATH=/data/tinyauth.db
      - TINYAUTH_ANALYTICS_ENABLED=false
      - TINYAUTH_LOG_LEVEL=info
      - TINYAUTH_SERVER_PORT=3000
      - TINYAUTH_SERVER_ADDRESS=0.0.0.0
      - TINYAUTH_AUTH_USERSFILE=/users/users.txt
      - TINYAUTH_AUTH_SECURECOOKIE=true
      - TINYAUTH_AUTH_SESSIONEXPIRY=7200
      - TINYAUTH_AUTH_LOGINTIMEOUT=300
      - TINYAUTH_AUTH_LOGINMAXRETRIES=5
      - TINYAUTH_UI_TITLE=Hommers
      - TINYAUTH_UI_FORGOTPASSWORDMESSAGE=Wachtwoord vergeten? Ga naar "https://auth.hommers.nl/manage"
    volumes:
      - ./users:/users
      - ./data:/data
    networks:
      - traefik
    labels:
      traefik.enable: "true"
      traefik.http.routers.tinyauth.rule: Host(`auth.hommers.nl`)
      traefik.http.routers.tinyauth.entrypoints: websecure
      traefik.http.routers.tinyauth.tls.certresolver: letsencrypt
      traefik.http.routers.tinyauth.priority: "1"
      traefik.http.services.tinyauth.loadbalancer.server.port: "3000"
      traefik.http.middlewares.tinyauth.forwardauth.address: http://tinyauth:3000/api/auth/traefik

  sidecar:
    container_name: tinyauth-sidecar
    image: ghcr.io/frankhommers/tinyauth-sidecar:latest
    restart: unless-stopped
    environment:
      - USERS_FILE_PATH=/users/users.txt
      - USERS_TOML=/users/users.toml
      - TINYAUTH_CONTAINER_NAME=tinyauth
      - TINYAUTH_BASEURL=http://tinyauth:3000
      - DISABLE_SIGNUP=true
      - PORT=8080
      - CONFIG_PATH=/data/config.toml
    volumes:
      - ./users:/users
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik
    labels:
      traefik.enable: "true"
      traefik.http.routers.sidecar.rule: Host(`auth.hommers.nl`) && PathPrefix(`/manage`)
      traefik.http.routers.sidecar.entrypoints: websecure
      traefik.http.routers.sidecar.tls.certresolver: letsencrypt
      traefik.http.routers.sidecar.priority: "10"
      traefik.http.services.sidecar.loadbalancer.server.port: "8080"

networks:
  traefik:
    external: true
